on:
  push:
    branches:
      - develop
      - main

name: Deploy Carga Pontual
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Sync files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.ftp_host }}
          port: ${{ secrets.ftp_port }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          sftp_only: true
          local_path: './*'
          remote_path: '/datadrive/data/html/github-actions'          