name: deploy

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read
  
jobs:
  deploy:
    needs: trigger
    if: ${{ needs.trigger.outputs.continue == 'true' && needs.trigger.outputs.noop != 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: branch-deploy
      - uses: github/branch-deploy@v8.0.0            

      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.trigger.outputs.ref }}

      - name: Sync files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.ftp_host }}
          port: ${{ secrets.ftp_port }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          sftp_only: true
          local_path: './*'
          remote_path: '/datadrive/data/html/github-actions'