name: "branch deploy demo"

on:
  issue_comment:
    types: [created]

# Permissions needed for reacting and adding comments for IssueOps commands
permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read

jobs:
  demo:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:     
      - name: branch-deploy
        uses: github/branch-deploy@v8.0.0
        id: branch-deploy
        with:
          trigger: ".deploy"
     
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.branch-deploy.outputs.ref }}
     
      - name: fake noop deploy
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop == 'true' }}
        run: echo "I am doing a fake noop deploy"

      - name: Sync files
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' }}
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.ftp_host }}
          port: ${{ secrets.ftp_port }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          sftp_only: true
          local_path: './*'
          remote_path: '/datadrive/data/html/github-actions'             